"""Install a double-clickable launcher for this checkout.

On first server start a clone gets a real app entry without a separate setup
step. The launcher points at this checkout — not a copy of the code — so edits
here are what the icon runs. Re-install happens automatically if the checkout
moves and the old launcher still exists with a stale path.

  macOS:   ~/Applications/Portfolio.app  (and refresh Desktop if one is there)
  Windows: Start Menu + Desktop Portfolio.bat
  Linux:   ~/.local/share/applications/portfolio.desktop

Set PORTFOLIO_NO_APP_INSTALL=1 to skip. Failures never stop the server.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SCRIPT_SH = REPO / "scripts" / "make-desktop-shortcut.sh"
PYTHON = sys.executable


def ensure() -> None:
    if os.environ.get("PORTFOLIO_NO_APP_INSTALL"):
        return
    try:
        if sys.platform == "darwin":
            _ensure_macos()
        elif sys.platform == "win32":
            _ensure_windows()
        elif sys.platform.startswith("linux"):
            _ensure_linux()
    except Exception as exc:
        print(f"  app install skipped: {type(exc).__name__}: {exc}")


def _points_here(text: str, repo: Path = REPO) -> bool:
    # Quoted and bare forms both count — Windows bat uses cd /d "…", Linux
    # desktop uses Path=, macOS launcher uses cd "…".
    s = str(repo)
    return s in text or s.replace("\\", "/") in text


def _ensure_macos() -> None:
    app = Path.home() / "Applications" / "Portfolio.app"
    if not SCRIPT_SH.is_file():
        return
    if _macos_points_here(app):
        return
    app.parent.mkdir(parents=True, exist_ok=True)
    result = subprocess.run(
        ["bash", str(SCRIPT_SH), str(app)],
        capture_output=True, text=True, timeout=60,
    )
    if result.returncode != 0:
        err = (result.stderr or result.stdout or "").strip().splitlines()
        print(f"  app install skipped: {err[-1] if err else 'unknown error'}")
        return
    print(f"  installed app: {app}")
    desktop = Path.home() / "Desktop" / "Portfolio.app"
    if desktop.exists() and not _macos_points_here(desktop):
        subprocess.run(
            ["bash", str(SCRIPT_SH), str(desktop)],
            capture_output=True, text=True, timeout=60,
        )
        print(f"  updated: {desktop}")


def _macos_points_here(app: Path) -> bool:
    launcher = app / "Contents" / "MacOS" / "Portfolio"
    if not launcher.is_file():
        return False
    try:
        return _points_here(launcher.read_text("utf-8"))
    except OSError:
        return False


def _ensure_windows() -> None:
    log_dir = Path(os.environ.get("LOCALAPPDATA", str(Path.home()))) / "Portfolio"
    body = (
        "@echo off\r\n"
        "rem Generated by app/launcher.py — re-run the app to refresh.\r\n"
        f'cd /d "{REPO}" || exit /b 1\r\n'
        f'if not exist "{log_dir}" mkdir "{log_dir}"\r\n'
        f'"{PYTHON}" -u app\\server.py >> "{log_dir}\\portfolio-app.log" 2>&1\r\n'
    )
    targets = []
    appdata = os.environ.get("APPDATA")
    if appdata:
        targets.append(
            Path(appdata) / "Microsoft" / "Windows" / "Start Menu"
            / "Programs" / "Portfolio.bat"
        )
    targets.append(Path.home() / "Desktop" / "Portfolio.bat")

    for dest in targets:
        if dest.is_file():
            try:
                if _points_here(dest.read_text("utf-8", errors="replace")):
                    continue
            except OSError:
                pass
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(body, encoding="utf-8", newline="")
        print(f"  installed app: {dest}")


def _ensure_linux() -> None:
    apps = Path.home() / ".local" / "share" / "applications"
    dest = apps / "portfolio.desktop"
    # Escape only what the Desktop Entry spec requires inside a quoted Exec arg.
    py = PYTHON.replace("\\", "\\\\").replace('"', '\\"')
    repo = str(REPO).replace("\\", "\\\\").replace('"', '\\"')
    server = str(REPO / "app" / "server.py").replace("\\", "\\\\").replace('"', '\\"')
    body = (
        "[Desktop Entry]\n"
        "Version=1.0\n"
        "Type=Application\n"
        "Name=Portfolio\n"
        "Comment=Local investment portfolio tracker\n"
        f'Exec="{py}" -u "{server}"\n'
        f"Path={repo}\n"
        "Terminal=false\n"
        "Categories=Office;Finance;\n"
        "StartupNotify=false\n"
    )
    if dest.is_file():
        try:
            if _points_here(dest.read_text("utf-8")):
                return
        except OSError:
            pass
    apps.mkdir(parents=True, exist_ok=True)
    dest.write_text(body, encoding="utf-8")
    dest.chmod(dest.stat().st_mode | 0o111)
    print(f"  installed app: {dest}")
