#!/bin/bash
# Build a double-clickable Portfolio.app in Applications (macOS).
#
# The bundle is a launcher, not a copy: it points at this checkout, so editing
# the code changes what the icon starts. Re-run this script only if you move
# the repository. The server also installs this on first launch (macOS), so a
# fresh clone gets an app in Launchpad without a separate step.
#
# Default: ~/Applications/Portfolio.app
# Elsewhere:  bash scripts/make-desktop-shortcut.sh ~/Desktop/Portfolio.app

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP="${1:-$HOME/Applications/Portfolio.app}"

# Finder does not launch apps with your shell's PATH — it uses launchd's, which
# has no /opt/homebrew/bin in it. `env python3` therefore finds a different
# interpreter there than it does in a terminal, or none at all. Burn the path
# of the python3 that is actually being used into the launcher.
PYTHON="$(command -v python3 || true)"
if [ -z "$PYTHON" ]; then
  echo "No python3 on PATH — install it first." >&2
  exit 1
fi

mkdir -p "$(dirname "$APP")"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>Portfolio</string>
  <key>CFBundleDisplayName</key><string>Portfolio</string>
  <key>CFBundleIdentifier</key><string>local.investment.portfolio</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>Portfolio</string>
  <key>CFBundleIconFile</key><string>Portfolio</string>
  <!-- no Dock icon and no menu bar: this is a server with a browser window -->
  <key>LSUIElement</key><true/>
</dict>
</plist>
PLIST

cat > "$APP/Contents/MacOS/Portfolio" <<LAUNCHER
#!/bin/bash
# Generated by scripts/make-desktop-shortcut.sh — edit that, not this.
cd "$REPO" || exit 1
# -u: unbuffered, so the log is readable while it runs, not only after it dies
exec "$PYTHON" -u app/server.py >> "\$HOME/Library/Logs/portfolio-app.log" 2>&1
LAUNCHER
chmod +x "$APP/Contents/MacOS/Portfolio"

# Icon: drawn here so the bundle does not need a binary checked into git.
ICON_SRC="$(mktemp -d)/icon.png"
python3 - "$ICON_SRC" <<'PY'
import struct, sys, zlib

SIZE = 512
BG_TOP, BG_BOTTOM = (0x89, 0x50, 0xFC), (0x36, 0x99, 0xFF)   # violet -> blue
INK = (0xFF, 0xFF, 0xFF)

# A rising line over a rounded gradient square: the shape of the thing the app
# is for, with no text to go stale.
POINTS = [(0.16, 0.70), (0.34, 0.54), (0.48, 0.61), (0.64, 0.34), (0.82, 0.25)]
RADIUS = SIZE * 0.22
STROKE = SIZE * 0.05
DOT = STROKE * 0.72
AA = 1.2          # edge softness, in pixels


def rect_distance(x, y):
    """Signed distance to the rounded square: negative inside, zero on the edge."""
    half = SIZE / 2
    qx = abs(x - half) - (half - RADIUS)
    qy = abs(y - half) - (half - RADIUS)
    outside = (max(qx, 0.0) ** 2 + max(qy, 0.0) ** 2) ** 0.5
    return outside + min(max(qx, qy), 0.0) - RADIUS


def line_distance(x, y):
    best = 1e9
    for (x1, y1), (x2, y2) in zip(POINTS, POINTS[1:]):
        ax, ay, bx, by = x1 * SIZE, y1 * SIZE, x2 * SIZE, y2 * SIZE
        dx, dy = bx - ax, by - ay
        t = max(0.0, min(1.0, ((x - ax) * dx + (y - ay) * dy) / (dx * dx + dy * dy)))
        best = min(best, ((ax + t * dx - x) ** 2 + (ay + t * dy - y) ** 2) ** 0.5 - STROKE / 2)
    for px, py in POINTS:
        best = min(best, ((px * SIZE - x) ** 2 + (py * SIZE - y) ** 2) ** 0.5 - DOT)
    return best


def coverage(distance):
    """1 well inside the shape, 0 well outside, a soft ramp across the edge."""
    return max(0.0, min(1.0, 0.5 - distance / AA))


rows = bytearray()
for y in range(SIZE):
    rows.append(0)
    blend = y / (SIZE - 1)
    base = tuple(BG_TOP[i] + (BG_BOTTOM[i] - BG_TOP[i]) * blend for i in range(3))
    for x in range(SIZE):
        alpha = coverage(rect_distance(x + 0.5, y + 0.5))
        if alpha <= 0:
            rows.extend((0, 0, 0, 0))
            continue
        ink = coverage(line_distance(x + 0.5, y + 0.5))
        rows.extend(tuple(int(round(base[i] + (INK[i] - base[i]) * ink)) for i in range(3))
                    + (int(round(alpha * 255)),))


def chunk(tag, data):
    return (struct.pack(">I", len(data)) + tag + data
            + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))


png = (b"\x89PNG\r\n\x1a\n"
       + chunk(b"IHDR", struct.pack(">IIBBBBB", SIZE, SIZE, 8, 6, 0, 0, 0))
       + chunk(b"IDAT", zlib.compress(bytes(rows), 9))
       + chunk(b"IEND", b""))
open(sys.argv[1], "wb").write(png)
PY

ICONSET="$(mktemp -d)/Portfolio.iconset"
mkdir -p "$ICONSET"
for s in 16 32 128 256 512; do
  sips -z $s $s "$ICON_SRC" --out "$ICONSET/icon_${s}x${s}.png" >/dev/null
  sips -z $((s * 2)) $((s * 2)) "$ICON_SRC" --out "$ICONSET/icon_${s}x${s}@2x.png" >/dev/null
done
iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/Portfolio.icns"

# An unsigned bundle has no stable identity, and macOS will not even ASK it
# whether it may read a protected folder — it refuses, silently, with
# "Operation not permitted". An ad-hoc signature is identity enough for the
# permission prompt to appear and for the answer to stick.
if command -v codesign >/dev/null 2>&1; then
  codesign --force --deep --sign - "$APP" >/dev/null 2>&1 \
    && echo "Signed ad-hoc (so macOS can ask about folder access)" \
    || echo "codesign failed — first launch may be refused access to $REPO" >&2
fi

touch "$APP"   # nudge Finder into re-reading the bundle
echo "Created $APP"
echo "Starts: $REPO/app/server.py"
echo "Log:    $HOME/Library/Logs/portfolio-app.log"
