@echo off
rem Build a double-clickable Portfolio.bat (Windows).
rem
rem The file is a launcher, not a copy: it points at this checkout, so editing
rem the code changes what the icon starts. Re-run this script only if you move
rem the repository. The server also installs these on first launch, so a fresh
rem clone gets Start Menu + Desktop entries without a separate step.
rem
rem Defaults (no args): Start Menu AND Desktop.
rem One path:  scripts\make-desktop-shortcut.bat D:\Shortcuts\Portfolio.bat

setlocal EnableExtensions

for %%I in ("%~dp0..") do set "REPO=%%~fI"

rem A double-clicked .bat gets a short PATH, not the interactive shell's.
rem Burn in the interpreter that is actually available here - same reason the
rem macOS script writes an absolute python3 path into the .app launcher.
set "PYTHON="
where py >nul 2>&1 && for /f "delims=" %%P in ('py -3 -c "import sys; print(sys.executable)" 2^>nul') do set "PYTHON=%%P"
if not defined PYTHON where python >nul 2>&1 && for /f "delims=" %%P in ('python -c "import sys; print(sys.executable)" 2^>nul') do set "PYTHON=%%P"
if not defined PYTHON where python3 >nul 2>&1 && for /f "delims=" %%P in ('python3 -c "import sys; print(sys.executable)" 2^>nul') do set "PYTHON=%%P"

if not defined PYTHON (
  echo No python on PATH - install from python.org with "Add python.exe to PATH".
  exit /b 1
)

set "LOGDIR=%LOCALAPPDATA%\Portfolio"

if not "%~1"=="" (
  call :write_one "%~f1"
  goto :done
)

if defined APPDATA (
  call :write_one "%APPDATA%\Microsoft\Windows\Start Menu\Programs\Portfolio.bat"
)
call :write_one "%USERPROFILE%\Desktop\Portfolio.bat"

:done
echo Starts: %REPO%\app\server.py
echo Log:    %LOGDIR%\portfolio-app.log
exit /b 0

:write_one
set "DEST=%~1"
for %%D in ("%DEST%") do if not exist "%%~dpD" mkdir "%%~dpD"
> "%DEST%" (
  echo @echo off
  echo rem Generated by scripts\make-desktop-shortcut.bat - edit that, not this.
  echo cd /d "%REPO%" ^|^| exit /b 1
  echo if not exist "%LOGDIR%" mkdir "%LOGDIR%"
  echo rem -u: unbuffered, so the log is readable while it runs, not only after it dies
  echo "%PYTHON%" -u app\server.py ^>^> "%LOGDIR%\portfolio-app.log" 2^>^&1
)
echo Created %DEST%
goto :eof
